name: RPGPlus
main: com.Github.Malatak1.RPGPlus.RPGPlus
version: 0.1

commands:
  rpg:
    description: rpgplus base command
    usage: /<command>
  focus:
    description: adds focus enchantment
    usage: /<command> [level]
  party:
    description: party base command
    usage: /<command> (join/leave/create/invite/disband) [args]